name: Deploy to gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install NPM packages
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Deploy
        run: npm run deploy
